export const events = [
  {
    id: 1,
    title: "Tech Meetup",
    description: "Discuss AI, web development, and startup ideas.",
    locationName: "ICT Lab 1",
    date: "2026-04-10",
    time: "14:00 - 17:00",
    status: "ongoing",
    category: "Technology",
    image: "https://via.placeholder.com/300",
    organizer: "Computer Science Dept",
  },
  {
    id: 2,
    title: "Campus Worship",
    description: "Evening praise and worship session.",
    locationName: "University Auditorium",
    date: "2026-04-11",
    time: "18:00 - 20:00",
    status: "upcoming",
    category: "Religious",
    image: "https://via.placeholder.com/300",
    organizer: "Student Fellowship",
  },
  {
    id: 3,
    title: "Career Fair",
    description: "Meet recruiters and explore job opportunities.",
    locationName: "Postgraduate College",
    date: "2026-04-12",
    time: "10:00 - 15:00",
    status: "ended",
    category: "Career",
    image: "https://via.placeholder.com/300",
    organizer: "Career Services",
  },
  {
    id: 4,
    title: "Movie Night",
    description: "Outdoor movie screening with snacks.",
    locationName: "Peace Park",
    date: "2026-04-12",
    time: "20:00 - 23:00",
    status: "upcoming",
    category: "Entertainment",
    image: "https://via.placeholder.com/300",
    organizer: "Student Union",
  },
  {
    id: 5,
    title: "Hackathon",
    description: "24-hour coding challenge with prizes.",
    locationName: "ICT Lab 2",
    date: "2026-04-13",
    time: "09:00 - 09:00",
    status: "ongoing",
    category: "Technology",
    image: "https://via.placeholder.com/300",
    organizer: "Dev Club",
  },
  {
    id: 6,
    title: "Fitness Bootcamp",
    description: "Morning workout session.",
    locationName: "Gethsemane Garden",
    date: "2026-04-14",
    time: "06:30 - 08:00",
    status: "ended",
    category: "Health",
    image: "https://via.placeholder.com/300",
    organizer: "Sports Unit",
  },
  {
    id: 7,
    title: "Debate Competition",
    description: "Inter-faculty debate showdown.",
    locationName: "Faculty of Social Sciences",
    date: "2026-04-15",
    time: "12:00 - 14:00",
    status: "ongoing",
    category: "Academic",
    image: "https://via.placeholder.com/300",
    organizer: "Debate Club",
  },
  {
    id: 8,
    title: "Art Exhibition",
    description: "Display of creative student artworks.",
    locationName: "Boja Theatre Art",
    date: "2026-04-16",
    time: "11:00 - 16:00",
    status: "upcoming",
    category: "Art",
    image: "https://via.placeholder.com/300",
    organizer: "Arts Department",
  },
  {
    id: 9,
    title: "Food Festival",
    description: "Enjoy local and international dishes.",
    locationName: "Numbers Cafeteria",
    date: "2026-04-17",
    time: "13:00 - 18:00",
    status: "ended",
    category: "Food",
    image: "https://via.placeholder.com/300",
    organizer: "Hospitality Team",
  },
  {
    id: 10,
    title: "Health Awareness Talk",
    description: "Learn about mental and physical wellness.",
    locationName: "Health Center",
    date: "2026-04-18",
    time: "15:00 - 17:00",
    status: "upcoming",
    category: "Health",
    image: "https://via.placeholder.com/300",
    organizer: "Medical Unit",
  },
];